<?php

/**
 * @file
 * Provides media entities.
 */

/**
 * Implements hook_theme().
 */
function media_entity_theme() {
  return array(
    'media_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'media_entity.theme.inc',
      'template' => 'media-add-list',
    ),
    'media' => array(
      'render element' => 'elements',
      'file' => 'media_entity.theme.inc',
      'template' => 'media',
    ),
  );
}

/**
 * Copy the media file icons to files directory for use with image styles.
 *
 * @throws Exception
 */
function media_entity_copy_icons() {
  $destination = \Drupal::config('media_entity.settings')->get('icon_base');

  if (!file_prepare_directory($destination, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    throw new Exception("Unable to create directory $destination.");
  }

  $source = drupal_get_path('module', 'media_entity') . '/images/icons';
  $files = file_scan_directory($source, '/.*\.(png|jpg)$/');
  foreach ($files as $file) {
    $result = file_unmanaged_copy($file->uri, $destination, FILE_EXISTS_REPLACE);
    if (!$result) {
      throw new Exception("Unable to copy {$file->uri} to $destination.");
    }
  }
}
