<?php

/**
 * @file
 * Provides media entities.
 */

/**
 * Implements hook_theme().
 */
function media_entity_theme() {
  return [
    'media' => [
      'render element' => 'elements',
      'file' => 'media_entity.theme.inc',
      'template' => 'media',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function media_entity_theme_suggestions_media(array $variables) {
  $suggestions = [];
  $media = $variables['elements']['#media'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'media__' . $sanitized_view_mode;
  $suggestions[] = 'media__' . $media->bundle();
  $suggestions[] = 'media__' . $media->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'media__' . $media->id();
  $suggestions[] = 'media__' . $media->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Copy the media file icons to files directory for use with image styles.
 *
 * @param string $source
 *   Source folder.
 * @param string $destination
 *   Destination folder.
 *
 * @throws Exception
 */
function media_entity_copy_icons($source, $destination) {
  if (!file_prepare_directory($destination, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    throw new Exception("Unable to create directory $destination.");
  }

  $files = file_scan_directory($source, '/.*\.(png|jpg)$/');
  foreach ($files as $file) {
    $result = file_unmanaged_copy($file->uri, $destination, FILE_EXISTS_REPLACE);
    if (!$result) {
      throw new Exception("Unable to copy {$file->uri} to $destination.");
    }
  }
}
