media_entity.settings:
  type: config_object
  label: 'Media entity settings'
  mapping:
    icon_base:
      type: string
      label: 'Base folder for icons installation'

media_entity.bundle.*:
  type: config_entity
  label: 'Media bundle'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    type:
      type: string
      label: 'Type plugin ID'
    queue_thumbnail_downloads:
      type: boolean
      label: 'Queue thumbnail downloads'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: media_entity.bundle.third_party.[%key]
    type_configuration:
      type: media_entity.bundle.type.[%parent.type]
    field_map:
      type: mapping
      label: 'Field map'
